version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: cec
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cec
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data: